export const errorMessages: { [key: string]: string } = {
  P2000: 'The string is too short or too long for the specified field.',
  P2001: 'The record to update does not exist.',
  P2002: 'Unique constraint violation. Check your data.',
  P2003:
    'Foreign key constraint violation. Check the ID of the related object.',
  P2004: 'The record to delete does not exist.',
  P2005: 'The data type does not match.',
  P2006: 'The record is not unique.',
  P2010: 'The operation failed due to a foreign key constraint.',
  P2011: 'The provided value for the field is invalid.',
  P2012: 'The query was not valid.',
  P2013: 'The relation you are trying to create does not exist.',
  P2014: 'A required relation does not exist.',
  P2015: 'The model does not exist.',
  P2016: "The data provided does not match the model's expected structure.",
  P2017: 'The operation could not be completed due to a validation error.',
  P2018: 'The operation was canceled due to a deadlock.',
  P2019: 'The data provided is not unique, violating a unique constraint.',
  P2020: 'An error occurred while performing a query operation.',
  P2021: 'An unknown error occurred while accessing the database.',
  P2022: 'The operation failed due to a constraint violation.',
  P2023: 'The relation is missing in the provided data.',
  P2024: 'No records found for the specified criteria.',
  P2025: 'No records found to update or delete.',
  P2026: 'The provided value is too large.',
  P2027: 'The record already exists.',
  P2028: 'The foreign key references a non-existing record.',
  P2029: 'The operation cannot be performed due to a foreign key constraint.',
};
